test:
	touch zouttuestesthistoinput.txt
	rm zouttuestesthistoinput.txt
	touch zouttuestesthistoinput.txt
	grep EDITDISTS zouttuestestzork.txt | grep -v LEGEND >>zouttuestesthistoinput.txt
	grep DELETIONS zouttuestestzork.txt | grep -v LEGEND >>zouttuestesthistoinput.txt
	grep INSERTIONS zouttuestestzork.txt | grep -v LEGEND >>zouttuestesthistoinput.txt
	grep INSERTBYDIST zouttuestestzork.txt | grep -v LEGEND >>zouttuestesthistoinput.txt
	grep SIMILARITY zouttuestestzork.txt | grep -v LEGEND >>zouttuestesthistoinput.txt
	grep EDITDISTFRACTION zouttuestestzork.txt | grep -v TEXT >>zouttuestesthistoinput.txt
	grep SENTENCESBAGS zouttuestestzork.txt | grep -v TEXT >>zouttuestesthistoinput.txt
	grep PARACOUNTS zouttuestestzork.txt | grep -v TEXT >>zouttuestesthistoinput.txt
	grep SENTENCECOUNTS zouttuestestzork.txt | grep -v TEXT >>zouttuestesthistoinput.txt
	grep SENTENCELENGTH zouttuestestzork.txt | grep -v TEXT >>zouttuestesthistoinput.txt
	python histofromcomparison.py zouttuestesthistoinput.txt zouttuestesthistooutput.txt
	mv EditDistFracDraft.png EditDistFracDrafttest.png
	mv EditDistFracFinal.png EditDistFracFinaltest.png
	mv EditDistFracBagsDraftAgainstFinal.png EditDistFracBagsDraftAgainstFinaltest.png
#
101:
	touch zouttues101histoinput.txt
	rm zouttues101histoinput.txt
	touch zouttues101histoinput.txt
	grep EDITDISTS zouttues101zork.txt | grep -v LEGEND >>zouttues101histoinput.txt
	grep DELETIONS zouttues101zork.txt | grep -v LEGEND >>zouttues101histoinput.txt
	grep INSERTIONS zouttues101zork.txt | grep -v LEGEND >>zouttues101histoinput.txt
	grep INSERTBYDIST zouttues101zork.txt | grep -v LEGEND >>zouttues101histoinput.txt
	grep SIMILARITY zouttues101zork.txt | grep -v LEGEND >>zouttues101histoinput.txt
	grep EDITDISTFRACTION zouttues101zork.txt | grep -v TEXT >>zouttues101histoinput.txt
	grep SENTENCESBAGS zouttues101zork.txt | grep -v TEXT >>zouttues101histoinput.txt
	grep PARACOUNTS zouttues101zork.txt | grep -v TEXT >>zouttues101histoinput.txt
	grep SENTENCECOUNTS zouttues101zork.txt | grep -v TEXT >>zouttues101histoinput.txt
	grep SENTENCELENGTH zouttues101zork.txt | grep -v TEXT >>zouttues101histoinput.txt
	python histofromcomparison.py zouttues101histoinput.txt zouttues101histooutput.txt
	mv EditDistFracDraft.png EditDistFracDraft101.png
	mv EditDistFracFinal.png EditDistFracFinal101.png
	mv EditDistFracBagsDraftAgainstFinal.png EditDistFracBagsDraftAgainstFinal101.png
#
102:
	touch zouttues102histoinput.txt
	rm zouttues102histoinput.txt
	touch zouttues102histoinput.txt
	grep EDITDISTS zouttues102zork.txt | grep -v LEGEND >>zouttues102histoinput.txt
	grep DELETIONS zouttues102zork.txt | grep -v LEGEND >>zouttues102histoinput.txt
	grep INSERTIONS zouttues102zork.txt | grep -v LEGEND >>zouttues102histoinput.txt
	grep INSERTBYDIST zouttues102zork.txt | grep -v LEGEND >>zouttues102histoinput.txt
	grep SIMILARITY zouttues102zork.txt | grep -v LEGEND >>zouttues102histoinput.txt
	grep EDITDISTFRACTION zouttues102zork.txt | grep -v TEXT >>zouttues102histoinput.txt
	grep SENTENCESBAGS zouttues102zork.txt | grep -v TEXT >>zouttues102histoinput.txt
	grep PARACOUNTS zouttues102zork.txt | grep -v TEXT >>zouttues102histoinput.txt
	grep SENTENCECOUNTS zouttues102zork.txt | grep -v TEXT >>zouttues102histoinput.txt
	grep SENTENCELENGTH zouttues102zork.txt | grep -v TEXT >>zouttues102histoinput.txt
	python histofromcomparison.py zouttues102histoinput.txt zouttues102histooutput.txt
	mv EditDistFracDraft.png EditDistFracDraft102.png
	mv EditDistFracFinal.png EditDistFracFinal102.png
	mv EditDistFracBagsDraftAgainstFinal.png EditDistFracBagsDraftAgainstFinal102.png
#
cleantest:
	rm zouttuesEDITDISTSgrep.txt
	rm zouttuesDELETIONSgrep.txt
	rm zouttuesINSERTIONSgrep.txt
	rm zouttuesINSERTBYDISTgrep.txt
	rm zouttuesSIMILARITYgrep.txt
	rm zouttuesEDITDISTFRACTIONgrep.txt
	rm zouttuesSENTENCESBAGSgrep.txt
#
