test:
	python comparison.py ../FYECorpus/Test zoutmontest.txt
	grep ZORK zoutmontest.txt >zoutmontestzork.txt
	cp zoutmontestzork.txt ..
#
101:
	python comparison.py ../FYECorpus/101 zoutmon101.txt
	grep ZORK zoutmon101.txt >zoutmon101zork.txt
	cp zoutmon101zork.txt ..
#
102:
	python comparison.py ../FYECorpus/102 zoutmon102.txt
	grep ZORK zoutmon102.txt >zoutmon102zork.txt
	cp zoutmon102zork.txt ..
#
