#!/bin/bash
#
# The 'fileID' is the file name for the output, without
# and suffices.
#
# The 'whichInput' selects which directory in 'FYECorpus'
# to use as the directory for the input files.
#
# The script produces an output file named
#   'zout$(fileID)$(whichInput)$(whichParas).txt'
# and then it greps for the 'ZORK' input for the
# histograms, producing a file named
#   'zout$(fileID)$(whichInput)$(whichParas)zork.txt'
#
# arg 1 -- fileID
# arg 2 -- whichInput to use
# arg 3 -- whichParas to use -- ALL, FIRST, LAST, MIDDLE
# arg 4 -- whether to ALIGNBAGLIMIT or ALIGNBAGNO the alignment
#
if [ $# -ne 4 ]
then
  echo usage: fileID whichInput whichParas alignBagLimit
else
  echo "ZRUNIT: fileID=X"$1"X"
  echo "ZRUNIT: whichInput=X"$2"X"
  echo "ZRUNIT: outputfile=X"zout$1$2$3.txt"X" 
  echo "ZRUNIT: zorkfile=X"zout$1$2$3zork.txt"X"
#  exit 1
#
  if [ $2 == filter1 ]
  then
    echo "ZRUNIT: run filter1"
    let flag=1
  fi
#
  if [ $((flag)) -eq 0 ]
  then
    echo "ERROR IN whichInput VALUE=X"$2"X"
    exit 1
  fi
#
  echo "ZRUNIT: run python comparison.py ../FYECorpus/"$2 zout$1$2$3.txt
  python comparison.py ../../20154falltexts/ENGL101-016-FALL-2015/$2 zout$1$2$3.txt $3 $4
#  python comparison.py ../FYECorpus/$2 zout$1$2$3.txt $3 $4
#  python2.7 comparison.py ../FYECorpus/$2 zout$1$2$3.txt $3 $4
  echo "ZRUNIT: grep for ZORK"
  grep ZORK zout$1$2$3.txt >zout$1$2$3zork.txt 
  grep ZZNEW zout$1$2$3.txt >zout$1$2$3zznew.txt 
  grep DIVERS zout$1$2$3.txt >zout$1$2$3zzdiversity.txt 
  echo "ZRUNIT: copy zork to parent directory"
  cp zout$1$2$3zork.txt .. 
  cp zout$1$2$3zznew.txt .. 
  cp zout$1$2$3zzdiversity.txt .. 
#  rm zzzztemp*
fi

